// Code generated by "stringer -type=cinema"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Agrafka-0]
	_ = x[CityBonarka-1]
	_ = x[CityKazimierz-2]
	_ = x[CityZakopianka-3]
	_ = x[IMAX-4]
	_ = x[Kijow-5]
	_ = x[Kika-6]
	_ = x[Mikro-7]
	_ = x[PodBaranami-8]
	_ = x[Multikino-9]
	_ = x[Paradox-10]
	_ = x[Sfinks-11]
}

const _cinema_name = "AgrafkaCityBonarkaCityKazimierzCityZakopiankaIMAXKijowKikaMikroPodBaranamiMultikinoParadoxSfinks"

var _cinema_index = [...]uint8{0, 7, 18, 31, 45, 49, 54, 58, 63, 74, 83, 90, 96}

func (i cinema) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_cinema_index)-1 {
		return "cinema(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _cinema_name[_cinema_index[idx]:_cinema_index[idx+1]]
}
