// Code generated by "stringer -type=cinema"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Agrafka-0]
	_ = x[CCityBonarka-1]
	_ = x[CCityKazimierz-2]
	_ = x[CCityZakopianka-3]
	_ = x[Kijow-4]
	_ = x[Kika-5]
	_ = x[Mikro-6]
	_ = x[PodBaranami-7]
	_ = x[Multikino-8]
	_ = x[Paradox-9]
	_ = x[Sfinks-10]
	_ = x[LAST-11]
}

const _cinema_name = "AgrafkaCCityBonarkaCCityKazimierzCCityZakopiankaKijowKikaMikroPodBaranamiMultikinoParadoxSfinksLAST"

var _cinema_index = [...]uint8{0, 7, 19, 33, 48, 53, 57, 62, 73, 82, 89, 95, 99}

func (i cinema) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_cinema_index)-1 {
		return "cinema(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _cinema_name[_cinema_index[idx]:_cinema_index[idx+1]]
}
